const mockPricesList = {
  object: "list",
  data: [
    {
      id: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1706606465,
      currency: "nok",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PQvPpUEDyLZgwn",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 12000,
      unit_amount_decimal: "12000",
    },
    {
      id: "price_1ONiWZI4AFOXjzTCOfjbrleH",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702674143,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PC6k6sd0lDMrMs",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONiLKI4AFOXjzTCRFQD8upA",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702673446,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PC6Yh5tUbYzN6Q",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONiKtI4AFOXjzTCp4yFMISs",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702673419,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PC6XUmVtdWzWpy",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONiJaI4AFOXjzTC1H8GLWGI",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702673338,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PC6WscR3klIXwb",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONMDTI4AFOXjzTCXmKOHYgs",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702588391,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PBjgZCA4gQsgaW",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONMD0I4AFOXjzTC4uRuj8FC",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702588362,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PBjgatgLseTmOd",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONMCXI4AFOXjzTCmMjXLIzO",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702588333,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PBjfoi3JscRrLE",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONMCCI4AFOXjzTCbfNDtjWQ",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702588312,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PBjfj0QVc7M99y",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
    {
      id: "price_1ONMBNI4AFOXjzTCT9TFVs0I",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1702588261,
      currency: "usd",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_PBje7KltmLr48t",
      recurring: null,
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "one_time",
      unit_amount: 1500,
      unit_amount_decimal: "1500",
    },
  ],
  has_more: true,
  url: "/v1/prices",
};

export default mockPricesList;
