const mockProductsList = {
  object: "list",
  data: [
    {
      id: "prod_PQvPpUEDyLZgwn",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description: "Harvested from wildflowers in the Alpine meadows. test1",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "honey",
      },
      name: "Alpine Blossom Honey",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "honey",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUEDyLZgwn3",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description: "Harvested from wildflowers in the Alpine meadows. test1",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "honey",
      },
      name: "Alpine Blossom Honey 2",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "honey",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUEDyLZgwn5",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description: "Harvested from wildflowers in the Alpine meadows. test1",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "honey",
      },
      name: "Alpine Blossom Honey",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "honey",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUEDyLZgw7e",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description: "Harvested from wildflowers in the Alpine meadows test2.",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "honey",
      },
      name: "Alpine Blossom Honey 3",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "bee",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUED9yLZgwe",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description: "Harvested from wildflowers in the Alpine meadows test2.",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "honey",
      },
      name: "Alpine Blossom Honey 4",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "bee",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUE5DyLZgwe",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description:
        "Harvested from wildflowers in the Alpine meadows test2. honey",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "bee",
      },
      name: "Alpine Blossom Bee",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "bee",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPprUEDyLZgwe",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1OeDV7I4AFOXjzTChrCuNyDq",
      description:
        "Harvested from wildflowers in the Alpine meadows test2. bee",
      features: [],
      images: ["/images/honey.jpg"],
      livemode: false,
      metadata: {
        category: "bee",
      },
      name: "Alpine Blossom Bee 2",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "bee",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
  ],
  has_more: true,
  url: "/v1/products",
};

export default mockProductsList;
