const mockProductsList = {
  object: "list",
  data: [
    {
      id: "prod_PQvPpUEDyLZgwn",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1Oc3YXI4AFOXjzTClsRL4cRn",
      description: "Harvested from wildflowers in the Alpine meadows. test1",
      features: [],
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xT0dwc1RJNEFGT1hqelRDfGZsX3Rlc3RfQnZIcHEzNVV3bDlta210RDBLOTFiRXli00JA35wqUI",
      ],
      livemode: false,
      metadata: {},
      name: "Alpine Blossom Honey",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "honey",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
    {
      id: "prod_PQvPpUEDyLZgwe",
      object: "product",
      active: true,
      attributes: [],
      created: 1706091581,
      default_price: "price_1Oc3YXI4AFOXjzTClsRL4cRn",
      description: "Harvested from wildflowers in the Alpine meadows test2.",
      features: [],
      images: [
        "https://files.stripe.com/links/MDB8YWNjdF8xT0dwc1RJNEFGT1hqelRDfGZsX3Rlc3RfQnZIcHEzNVV3bDlta210RDBLOTFiRXli00JA35wqUI",
      ],
      livemode: false,
      metadata: {},
      name: "Alpine Blossom Honey 2",
      package_dimensions: null,
      shippable: null,
      statement_descriptor: null,
      tax_code: "txcd_20030000",
      type: "bee",
      unit_label: null,
      updated: 1706091582,
      url: null,
    },
  ],
  has_more: true,
  url: "/v1/products",
};

export default mockProductsList;
