const sessionStamp = "ok5IfX_0kGF6uBfaQdRQP";

const checkoutSession = {
  id: "evt_1OewEcI4AFOXjzTC99vcpfVU",
  object: "event",
  api_version: "2023-10-16",
  created: 1706778422,
  data: {
    object: {
      id: "cs_test_a1vWoKNOTDPNvIuAMqcyne9lVmm271bPnbLAJ5JVITwpZ7iXt8xMCl7miq",
      object: "checkout.session",
      after_expiration: null,
      allow_promotion_codes: null,
      amount_subtotal: 120000,
      amount_total: 120000,
      automatic_tax: { enabled: false, liability: null, status: null },
      billing_address_collection: null,
      cancel_url: "http://localhost:3000/cancel",
      client_reference_id: null,
      client_secret: null,
      consent: null,
      consent_collection: null,
      created: 1706778392,
      currency: "nok",
      currency_conversion: null,
      custom_fields: [],
      custom_text: {
        after_submit: null,
        shipping_address: null,
        submit: null,
        terms_of_service_acceptance: null,
      },
      customer: null,
      customer_creation: "if_required",
      customer_details: {
        address: {
          city: null,
          country: "NO",
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: "mail@mail.com",
        name: "Name Namesen",
        phone: null,
        tax_exempt: "none",
        tax_ids: [],
      },
      customer_email: null,
      expires_at: 1706864792,
      invoice: null,
      invoice_creation: {
        enabled: false,
        invoice_data: {
          account_tax_ids: null,
          custom_fields: null,
          description: null,
          footer: null,
          issuer: null,
          metadata: {},
          rendering_options: null,
        },
      },
      livemode: false,
      locale: null,
      metadata: { user_id: "123", sessionStamp: "ok5IfX_0kGF6uBfaQdRQP" },
      mode: "payment",
      payment_intent: "pi_3OewEaI4AFOXjzTC018gLSPj",
      payment_link: null,
      payment_method_collection: "if_required",
      payment_method_configuration_details: {
        id: "pmc_1OKS5lI4AFOXjzTC6yK4i3Q4",
        parent: null,
      },
      payment_method_options: {},
      payment_method_types: ["card", "klarna", "link"],
      payment_status: "paid",
      phone_number_collection: { enabled: false },
      recovered_from: null,
      setup_intent: null,
      shipping_address_collection: null,
      shipping_cost: null,
      shipping_details: null,
      shipping_options: [],
      status: "complete",
      submit_type: null,
      subscription: null,
      success_url: "http://localhost:3000/thank-you?id=ok5IfX_0kGF6uBfaQdRQP",
      total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
      ui_mode: "hosted",
      url: null,
    },
  },
  livemode: false,
  pending_webhooks: 3,
  request: { id: null, idempotency_key: null },
  type: "checkout.session.completed",
};

const payment_intent_succeeded = {
  id: "evt_3OewEaI4AFOXjzTC03NqFkf5",
  object: "event",
  api_version: "2023-10-16",
  created: 1706778421,
  data: {
    object: {
      id: "pi_3OewEaI4AFOXjzTC018gLSPj",
      object: "payment_intent",
      amount: 120000,
      amount_capturable: 0,
      amount_details: { tip: {} },
      amount_received: 120000,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: "automatic",
      client_secret:
        "pi_3OewEaI4AFOXjzTC018gLSPj_secret_55jf5KpFFBAHYMOWEVUpDA0na",
      confirmation_method: "automatic",
      created: 1706778420,
      currency: "nok",
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: "ch_3OewEaI4AFOXjzTC01vrOnIS",
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: "pm_1OewEaI4AFOXjzTC2tPtOB9u",
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: "automatic",
        },
      },
      payment_method_types: ["card"],
      processing: null,
      receipt_email: "mail@mail.com",
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "succeeded",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: "req_St0mt66NVvHVDR",
    idempotency_key: "8be381c1-638e-49eb-b4a6-a221cb7bb4fe",
  },
  type: "payment_intent.succeeded",
};

const charge = {
  id: "evt_3OewEaI4AFOXjzTC09jXVP9l",
  object: "event",
  api_version: "2023-10-16",
  created: 1706778421,
  data: {
    object: {
      id: "ch_3OewEaI4AFOXjzTC01vrOnIS",
      object: "charge",
      amount: 120000,
      amount_captured: 120000,
      amount_refunded: 0,
      application: null,
      application_fee: null,
      application_fee_amount: null,
      balance_transaction: "txn_3OewEaI4AFOXjzTC027azCx4",
      billing_details: {
        address: {
          city: null,
          country: "NO",
          line1: null,
          line2: null,
          postal_code: null,
          state: null,
        },
        email: "mail@mail.com",
        name: "Name Namesen",
        phone: null,
      },
      calculated_statement_descriptor: "URL.COM",
      captured: true,
      created: 1706778421,
      currency: "nok",
      customer: null,
      description: null,
      destination: null,
      dispute: null,
      disputed: false,
      failure_balance_transaction: null,
      failure_code: null,
      failure_message: null,
      fraud_details: {},
      invoice: null,
      livemode: false,
      metadata: {},
      on_behalf_of: null,
      order: null,
      outcome: {
        network_status: "approved_by_network",
        reason: null,
        risk_level: "normal",
        risk_score: 43,
        seller_message: "Payment complete.",
        type: "authorized",
      },
      paid: true,
      payment_intent: "pi_3OewEaI4AFOXjzTC018gLSPj",
      payment_method: "pm_1OewEaI4AFOXjzTC2tPtOB9u",
      payment_method_details: {
        card: {
          amount_authorized: 120000,
          brand: "visa",
          checks: {
            address_line1_check: null,
            address_postal_code_check: null,
            cvc_check: "pass",
          },
          country: "US",
          exp_month: 4,
          exp_year: 2044,
          extended_authorization: { status: "disabled" },
          fingerprint: "B3Ldw2RNz1JjmfzV",
          funding: "credit",
          incremental_authorization: { status: "unavailable" },
          installments: null,
          last4: "4242",
          mandate: null,
          multicapture: { status: "unavailable" },
          network: "visa",
          network_token: { used: false },
          overcapture: {
            maximum_amount_capturable: 120000,
            status: "unavailable",
          },
          three_d_secure: null,
          wallet: null,
        },
        type: "card",
      },
      radar_options: {},
      receipt_email: "mail@mail.com",
      receipt_number: null,
      receipt_url:
        "https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xT0dwc1RJNEFGT1hqelRDKLa-7a0GMgYft2_2d4U6LBYMXUzkDokoXcsK7U2r9VsFQkm61eR76iY5HomLzpYQYGucS9l75qI9em_Q",
      refunded: false,
      review: null,
      shipping: null,
      source: null,
      source_transfer: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "succeeded",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: "req_St0mt66NVvHVDR",
    idempotency_key: "8be381c1-638e-49eb-b4a6-a221cb7bb4fe",
  },
  type: "charge.succeeded",
};

const payment_intent_created = {
  id: "evt_3OewEaI4AFOXjzTC0MIfgLfG",
  object: "event",
  api_version: "2023-10-16",
  created: 1706778420,
  data: {
    object: {
      id: "pi_3OewEaI4AFOXjzTC018gLSPj",
      object: "payment_intent",
      amount: 120000,
      amount_capturable: 0,
      amount_details: { tip: {} },
      amount_received: 0,
      application: null,
      application_fee_amount: null,
      automatic_payment_methods: null,
      canceled_at: null,
      cancellation_reason: null,
      capture_method: "automatic",
      client_secret:
        "pi_3OewEaI4AFOXjzTC018gLSPj_secret_55jf5KpFFBAHYMOWEVUpDA0na",
      confirmation_method: "automatic",
      created: 1706778420,
      currency: "nok",
      customer: null,
      description: null,
      invoice: null,
      last_payment_error: null,
      latest_charge: null,
      livemode: false,
      metadata: {},
      next_action: null,
      on_behalf_of: null,
      payment_method: null,
      payment_method_configuration_details: null,
      payment_method_options: {
        card: {
          installments: null,
          mandate_options: null,
          network: null,
          request_three_d_secure: "automatic",
        },
      },
      payment_method_types: ["card"],
      processing: null,
      receipt_email: null,
      review: null,
      setup_future_usage: null,
      shipping: null,
      source: null,
      statement_descriptor: null,
      statement_descriptor_suffix: null,
      status: "requires_payment_method",
      transfer_data: null,
      transfer_group: null,
    },
  },
  livemode: false,
  pending_webhooks: 2,
  request: {
    id: "req_St0mt66NVvHVDR",
    idempotency_key: "8be381c1-638e-49eb-b4a6-a221cb7bb4fe",
  },
  type: "payment_intent.created",
};
