name: e2e tests

on: push
env:
  NEXT_PUBLIC_TEST: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      NEXT_PUBLIC_TEST: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
